server:
  port: 12000
spring:
  application:
    name: sso-configs
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/doujiangloveyoutiao/config-test
          force-pull: false
          username: 786063250@qq.com
          password: 13673180154jia

