server:
  port: 9097
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sso-auth
  sleuth:
    trace-id128: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false