server:
  port: 9091
spring:
  application:
    name: sso-base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sso_new?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  zipkin:
    base-url: http://localhost:9097
  cloud:
    config:
      uri: http://localhost:12000/
      profile: default
      label: master
  rabbitmq:
    username: hexin
    password: hexin
    host: 172.16.10.197
    virtual-host: hexin
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://dev1:1111/eureka/,http://dev2:1112/eureka/,http://dev3:1113/eureka/
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
