server:
  port: 9093
spring:
  application:
    name: sso-web-zuul
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
zuul:
  routes:
    sso-base:
      path: /base/**
      serrviceId: sso-base
    sso-oauth:
      path: /aouth/**
      serrviceId: sso-oauth
